<nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
    <div class="navbar-multiline mr-auto">
        <span class="navbar-brand" href="#0">Photobooth Editor</span>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Photobooth</li>
            </ol>
        </nav>
    </div>
    <a href="<?= $this->router->to('adminPhotoboothEdit', ['id'=>0]) ?>" class="btn btn-primary">Create New</a>
</nav>

<div class="container p-3">
    <div class="row">
        <div class="col-md-3">
            <div class="card mb-3">
                <form method="GET" class="card-body">
                    <h5 class="card-title">Search</h5>
                    <?= $form->field('q') ?>
                    <?php if(module_exists('admin-photobooth-event')): ?>
                        <?= $form->field('event', $event) ?>
                    <?php endif; ?>
                    <div class="text-right">
                        <button class="btn btn-primary">Find</button>
                    </div>
                </form>
            </div>
            <div class="card mb-3">
                <div class="card-body">
                    <div>Total item: <?= number_format($total); ?></div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <?php $smsable = module_exists('admin-photobooth-text'); ?>
            <?php if($pbooths): ?>
                <?php $csrf = $form->csrfToken(); ?>
                <ul class="list-group list-group-flush card mb-3">
                    <?php foreach($pbooths as $pbooth): ?>
                        <li class="list-group-item" id="pbooth-<?= $pbooth->id ?>">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">
                                    <?= $pbooth->fullname->safe ?> <small>( <?= $pbooth->phone->safe ?> )</small>
                                </h5>
                                <div>
                                    <div class="btn-group btn-group-sm" role="group" aria-label="Action">
                                        <a href="<?= $this->router->to('adminPhotoboothEdit', ['id'=>$pbooth->id]) ?>" class="btn btn-secondary" title="Edit">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <?php if($smsable): ?>
                                        <a href="#" class="btn btn-secondary btn-sms" data-id="<?= $pbooth->id ?>" title="Send SMS">
                                            <i class="fas fa-sms"></i>
                                        </a>
                                        <?php endif; ?>
                                        <div class="btn-group btn-group-sm" role="group">
                                            <button id="pbooth-action-<?= $pbooth->id ?>" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                                            <div class="dropdown-menu" aria-labelledby="pbooth-action-<?= $pbooth->id ?>">
                                                <a class="dropdown-item"
                                                    data-toggle="confirm"
                                                    data-text="Are you sure want to remove this item?"
                                                    data-btn-type="danger"
                                                    href="<?= $this->router->to('adminPhotoboothRemove', ['id'=>$pbooth->id], ['noob'=>$csrf]) ?>">Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <small>
                                <span title="Created">
                                    <i class="far fa-calendar-plus"></i>
                                    <?= $pbooth->created->format('M d, Y H:i') ?>
                                </span>
                                &middot;
                                <span title="Creator">
                                    <i class="fas fa-user"></i>
                                    <?= $pbooth->user->fullname->safe ?>
                                </span>
                                <?php if($smsable): ?>
                                    &middot;
                                    <span title="Texted">
                                        <i class="fas fa-sms"></i>
                                        <span id="phbooth-sms-<?= $pbooth->id ?>"><?= $pbooth->texted->format() ?></span>
                                    </span>
                                <?php endif; ?>
                                <?php if(isset($pbooth->event) && is_object($pbooth->event)): ?>
                                    <br>
                                    <i class="fas fa-calendar-week"></i>
                                    <?php if(isset($pbooth->event->page)): ?>
                                        <a href="<?= $pbooth->event->page ?>" target="_blank"><?= $pbooth->event->title->safe ?></a>
                                    <?php else: ?>
                                        <?= $pbooth->event->title->safe ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </small>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <?php if($pages): ?>
                <?= $this->partial('shared/pagination', ['pages'=>$pages, 'align'=>'right']); ?>
            <?php endif; ?>
        </div>
    </div>
</div>


<?php if($smsable): ?>
<script>
    document.addEventListener('DOMContentLoaded', function(){
        $('.btn-sms').click(function(){
            var id     = $(this).data('id');
            var modal  = $('#modal-sms');
            var action = modal.data('action').replace('-id-', id);
            
            modal.attr('action', action);

            // set the text
            $('#admin-photobooth-sms-fld-content').val('TODO');

            $('#modal-sms').modal();
            return false;
        });
        <?php if($sms_error = $this->req->get('sms-error')): ?>
        $.dialog.alert('Whoops!', '<?= hs($sms_error) ?>');
        <?php endif; ?>
    }, false);
</script>
<form method="POST" class="modal fade" tabindex="-1" role="dialog" id="modal-sms" data-action="<?= $this->router->to('adminPhotoboothText', ['id'=>'-id-']) ?>">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Send SMS</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <?= $sms_form->csrfField('noob') ?>
                <?= $sms_form->field('content') ?>
                <?php $reff = preg_replace('![\?&]sms-error=.+!', '', $this->req->url); ?>
                <input type="hidden" name="reff" value="<?= hs($reff) ?>">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button class="btn btn-primary">Send</button>
            </div>
        </div>
    </div>
</form>
<?php endif; ?>